#######################################################################################
# Book settings
title                       : "The Way of the Cyber Warrior: Tactical Cyber Threat Response"  # The title of the book. Will be placed in the left navbar.
author                      : Diego Perez  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : "./figures/logo/cyber-punk-mf_v7j5mi.png"  # A path to the book logo
email                       : "darkquasar7@gmail.com"
exclude_patterns            : ["LICENSE.md"]  # Patterns to skip when building the book. Can be glob-style (for example "*skip.ipynb")

# Information about where the book exists on the web
description: >-
  Investigations into the transient fluctuations of reality in the cybersphere.
  
#######################################################################################
# Execution settings
execute:
  execute_notebooks         : force  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ["LICENSE.md"]  # A list of patterns to *skip* in execution (for example a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "./figures/logo/favicon-32x32.png"  # A path to a favicon image
  navbar_number_sections    : False  # Add a number to each section in your left navbar
  google_analytics_id       : "UA-167881009-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_repository_button     : true  # Whether to add an "Repository" button to pages. If `true`, repository information in repository: must be filled in
  use_issues_button         : true # Whether to add an "Open issue" button to pages. If `true`, repository information in repository: must be filled in
  use_edit_page_button      : true  # Whether to add an "Suggest edit" button to pages. If `true`, repository information in repository: must be filled in
  baseurl                   : "https://threathunterz.com/book"  # The base URL where your book will be hosted. Used for creating image previews and social links. for example: https://mypage.com/mybook/
  extra_navbar              : Visit our <a href="https://github.com/darkquasar/book.threathunterz.com">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>
  comments:
    hypothesis: true 

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (for example, https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (for example, https://datahub.berkeley.edu)
  thebelab                  : false  # Add a thebelab button to pages (requires the repository to run on Binder)

repository:
  url                       : https://github.com/darkquasar/book.threathunterz.com # The URL to your book's repository
  path_to_book              : "dabook"  # A path to your book's folder, relative to the repository root.

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :  # A list of extra extensions to load by Sphinx.
  config                    :  # key-value pairs to directly over-ride the Sphinx configuration
  
  
binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex 
